# Generated by Django 6.0.6 on 2026-10-01 10:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installation_id', models.UUIDField(unique=True)),
                ('app_version', models.CharField(max_length=40)),
                ('device_label', models.CharField(blank=True, max_length=120)),
                ('platform', models.CharField(default='android', max_length=16)),
                ('protocol_version', models.PositiveSmallIntegerField(default=1)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MobileDeviceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobile_sync.mobiledevice')),
            ],
        ),
        migrations.CreateModel(
            name='MobileSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobile_sync.mobiledevice')),
            ],
        ),
        migrations.CreateModel(
            name='SyncStreamState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('deployment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('epoch', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sequence', models.PositiveBigIntegerField(default=0)),
                ('minimum_sequence', models.PositiveBigIntegerField(default=0)),
                ('ready', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='sync_singleton')],
            },
        ),
        migrations.CreateModel(
            name='SyncBootstrap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epoch', models.UUIDField()),
                ('scope_revision', models.CharField(max_length=64)),
                ('packs', models.JSONField()),
                ('watermark', models.PositiveBigIntegerField()),
                ('row_count', models.PositiveIntegerField()),
                ('manifest', models.JSONField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobile_sync.mobiledevice')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobile_sync.syncstreamstate')),
            ],
        ),
        migrations.CreateModel(
            name='SyncBootstrapPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='mobile_sync.syncbootstrap')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'number'), name='sync_bootstrap_page')],
            },
        ),
        migrations.CreateModel(
            name='SyncOperationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('command', models.JSONField()),
                ('outcome', models.CharField(max_length=32)),
                ('result', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobile_sync.mobiledevice')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobile_sync.syncstreamstate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stream', 'actor', 'operation_id'), name='sync_operation_identity')],
            },
        ),
        migrations.CreateModel(
            name='SyncEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=40)),
                ('source_pk', models.CharField(max_length=64)),
                ('entity_uuid', models.UUIDField(default=uuid.uuid4)),
                ('batch_pk', models.CharField(max_length=64)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('deleted', models.BooleanField(default=False)),
                ('in_current_pack', models.BooleanField(default=False)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobile_sync.syncstreamstate')),
            ],
            options={
                'indexes': [models.Index(fields=['stream', 'batch_pk'], name='sync_entity_batch')],
                'constraints': [models.UniqueConstraint(fields=('stream', 'entity_type', 'source_pk'), name='sync_source_identity'), models.UniqueConstraint(fields=('stream', 'entity_uuid'), name='sync_uuid_identity')],
            },
        ),
        migrations.CreateModel(
            name='SyncChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField()),
                ('transaction_id', models.UUIDField()),
                ('transaction_index', models.PositiveIntegerField()),
                ('transaction_count', models.PositiveIntegerField()),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_uuid', models.UUIDField()),
                ('batch_uuid', models.UUIDField()),
                ('revision', models.PositiveBigIntegerField()),
                ('kind', models.CharField(max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('in_current_pack', models.BooleanField(default=False)),
                ('origin_operation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobile_sync.syncstreamstate')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['stream', 'created_at'], name='sync_change_retention')],
                'constraints': [models.UniqueConstraint(fields=('stream', 'sequence'), name='sync_change_sequence')],
            },
        ),
    ]
