# Generated by Django 6.0.6 on 2026-07-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('bird_type', models.CharField(choices=[('broilers', 'Broilers'), ('layers', 'Layers'), ('local', 'Local'), ('kloilers', 'Kloilers'), ('mikolongwe', 'Mikolongwe')], default='broilers', max_length=200)),
                ('entry_date', models.DateTimeField()),
                ('expected_maturity_date', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
