# Generated by Django 6.0.6 on 2026-07-08 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_measurement', models.CharField(choices=[('kg', 'KG'), ('meters', 'Meters'), ('inches', 'Inches'), ('gauge', 'Gauge')], max_length=200)),
                ('unit_cost', models.PositiveIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input', to='poultry.batch')),
            ],
        ),
    ]
