# Generated by Django 6.0.6 on 2026-07-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0002_inputcosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputcosts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-06-29 10:35:43.842 +0200'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputcosts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
