# Generated by Django 6.0.6 on 2026-07-08 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0003_inputcosts_created_at_inputcosts_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_date', models.DateField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sequence_date'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inputcosts',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inputs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inputcosts',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_costs', to='poultry.batch'),
        ),
        migrations.AlterField(
            model_name='inputcosts',
            name='unit_measurement',
            field=models.CharField(max_length=200),
        ),
    ]
