# Generated by Django 6.0.6 on 2026-07-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0004_batchidsequence_batch_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputcosts',
            name='unit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
