# Generated by Django 6.0.6 on 2026-07-09 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0005_inputcosts_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_date', models.DateField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sequence_date'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('sale_date', models.DateTimeField()),
                ('product_type', models.CharField(choices=[('live_chicken', 'Live Chicken'), ('dressed_chicken', 'Dressed Chicken'), ('eggs', 'Eggs'), ('manure', 'Manure')], max_length=20)),
                ('quantity_sold', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('buyer_name', models.CharField(max_length=200)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('loan', 'Loan'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled')], max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit')], max_length=200)),
                ('amount_paid', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField()),
                ('sold_by_name', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_row', to='poultry.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
