# Generated by Django 6.0.6 on 2026-07-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0006_saleidsequence_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='buyer_type',
            field=models.CharField(choices=[('market_vendor', 'Market Vendor'), ('retail', 'Retail'), ('retail_supply', 'Retail Supply'), ('bulk_order', 'Bulk Order')], default='market_vendor', max_length=20),
            preserve_default=False,
        ),
    ]
