# Generated by Django 6.0.6 on 2026-07-09 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0007_sales_buyer_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mortality_date', models.DateTimeField(auto_now_add=True)),
                ('quantity_dead', models.PositiveIntegerField()),
                ('age_in_days', models.PositiveIntegerField()),
                ('suspected_cause', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action_taken', models.TextField()),
                ('reported_by_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_row', to='poultry.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mortality', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
