# Generated by Django 6.0.6 on 2026-07-09 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0008_mortality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_age', models.PositiveIntegerField()),
                ('feeding_start_date', models.DateTimeField(auto_now_add=True)),
                ('feeding_end_date', models.DateTimeField(auto_now_add=True)),
                ('feed_type', models.CharField(choices=[('pre_starter', 'Pre-Starter'), ('starter', 'STARTER'), ('grower', 'Grower'), ('finisher', 'Finisher'), ('pullet_starter', 'Pullet Starter'), ('pullet_grower', 'Pullet Grower'), ('layers_marsh', 'Layers Marsh'), ('layers_finisher', 'Layers Finisher')], max_length=200)),
                ('feed_source', models.CharField(max_length=200)),
                ('quantity_given', models.PositiveIntegerField()),
                ('unit_of_measurement', models.CharField(max_length=200)),
                ('current_number_of_birds', models.PositiveIntegerField()),
                ('notes', models.TextField()),
                ('reported_by_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_usage_row', to='poultry.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feed_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
