# Generated by Django 6.0.6 on 2026-07-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0009_feedusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedusage',
            name='feed_source',
            field=models.CharField(choices=[('cp_feed', 'CP Feed'), ('proto_feed', 'Proto Feed'), ('concentrates_feed', 'Concentrates Feed'), ('self_made', 'Self Made')], max_length=200),
        ),
    ]
