# Generated by Django 6.0.6 on 2026-07-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0010_alter_feedusage_feed_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedusage',
            name='unit_of_measurement',
            field=models.CharField(choices=[('kg', 'KG'), ('g', 'Grams')], max_length=200),
        ),
    ]
