# Generated by Django 6.0.6 on 2026-07-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0011_alter_feedusage_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedusage',
            name='feeding_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='feedusage',
            name='feeding_start_date',
            field=models.DateTimeField(),
        ),
    ]
