# Generated by Django 6.0.6 on 2026-07-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0013_batch_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='source',
            field=models.CharField(choices=[('central_poultry', 'Central Poultry'), ('proto', 'Proto'), ('other', 'Other')], default='proto', max_length=200),
        ),
    ]
