# Generated by Django 6.0.6 on 2026-07-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0016_batch_source_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortality',
            name='mortality_date',
            field=models.DateTimeField(),
        ),
    ]
