# Generated by Django 6.0.6 on 2026-07-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0017_alter_mortality_mortality_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputcosts',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, default='2026-07-12 16:43:23.217 +0200'),
            preserve_default=False,
        ),
    ]
