# Generated by Django 6.0.6 on 2026-07-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0018_inputcosts_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputcosts',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
