# Generated by Django 6.0.6 on 2026-07-13 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0019_alter_inputcosts_purchase_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inputcosts',
            name='notes',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DrugsVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_date', models.DateTimeField()),
                ('drug_vaccination_type', models.CharField(choices=[('gumbolo', 'Gumbolo'), ('hitchner', 'Hitchner'), ('lasota', 'Lasota'), ('other', 'Other')], max_length=200)),
                ('other_drug_vaccination', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('reported_by_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_row', to='poultry.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vaccination', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
