# Generated by Django 6.0.6 on 2026-07-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0020_inputcosts_notes_drugsvaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugsvaccination',
            name='timely_status',
            field=models.CharField(default='on time', max_length=200),
            preserve_default=False,
        ),
    ]
