# Generated by Django 6.0.6 on 2026-07-17 09:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models
from django.db.models import Max, Sum
from django.utils import timezone


def backfill_batch_status(apps, schema_editor):
    batch_model = apps.get_model("poultry", "Batch")
    sales_model = apps.get_model("poultry", "Sales")
    mortality_model = apps.get_model("poultry", "Mortality")
    today = timezone.localdate()

    bird_products = {"live_chicken", "dressed_chicken"}

    for batch in batch_model.objects.all().iterator():
        sold = (
            sales_model.objects.filter(
                batch_id=batch.pk,
                product_type__in=bird_products,
            )
            .exclude(payment_status="cancelled")
            .aggregate(total=Sum("quantity_sold"))["total"]
            or 0
        )
        mortality = (
            mortality_model.objects.filter(batch_id=batch.pk).aggregate(
                total=Sum("quantity_dead")
            )["total"]
            or 0
        )
        remaining = batch.quantity - sold - mortality

        update_fields = ["status"]
        if remaining <= 0:
            last_sale_date = (
                sales_model.objects.filter(
                    batch_id=batch.pk,
                    product_type__in=bird_products,
                )
                .exclude(payment_status="cancelled")
                .aggregate(value=Max("sale_date"))["value"]
            )
            last_mortality_date = mortality_model.objects.filter(
                batch_id=batch.pk
            ).aggregate(value=Max("mortality_date"))["value"]
            closed_at = max(
                [value for value in [last_sale_date, last_mortality_date] if value],
                default=timezone.now(),
            )
            batch.status = "closed"
            batch.closed_at = closed_at
            batch.closure_reason = "Backfilled: remaining live birds reached zero."
            update_fields.extend(["closed_at", "closure_reason"])
        elif sold > 0:
            batch.status = "selling"
        elif batch.entry_date.date() > today:
            batch.status = "planned"
        elif batch.expected_maturity_date.date() <= today:
            batch.status = "mature"
        else:
            batch.status = "active"

        batch.save(update_fields=update_fields)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0022_drugsvaccination_drug_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='closure_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='batch',
            name='closure_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='batch',
            name='profitability_finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('mature', 'Mature'), ('selling', 'Selling'), ('closed', 'Closed')], db_index=True, default='planned', max_length=20),
        ),
        migrations.AddField(
            model_name='batch',
            name='target_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.RunPython(backfill_batch_status, noop_reverse),
        migrations.AlterField(
            model_name='inputcosts',
            name='unit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inputcosts',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='sales',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='sales',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
