# Generated by Django 6.0.6 on 2026-07-24 19:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0023_batch_closed_at_batch_closure_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='estimated_chick_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputcosts',
            name='usd_equivalent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='inputcosts',
            name='usd_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='MWK per USD at entry time.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AddField(
            model_name='sales',
            name='usd_equivalent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='sales',
            name='usd_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='MWK per USD at entry time.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
    ]
