# Generated by Django 6.0.6 on 2026-07-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0024_batch_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='delivery_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('planned', 'Planned'), ('delivered', 'Delivered at farm'), ('active', 'Active'), ('mature', 'Mature'), ('selling', 'Selling'), ('closed', 'Closed')], db_index=True, default='planned', max_length=20),
        ),
    ]
