# Generated by Django 6.0.6 on 2026-08-23 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0026_sales_buyer_type_other_and_other_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='broiler_strain',
            field=models.CharField(choices=[('ross308', 'Ross 308'), ('cobb500', 'Cobb 500')], default='ross308', help_text='For broilers only. Used for target weight curves.', max_length=20),
        ),
        migrations.CreateModel(
            name='BatchWeightSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_in_days', models.PositiveIntegerField(help_text='Age in days since entry (0 on placement day).')),
                ('sampled_at', models.DateTimeField(help_text='When the weighing took place.')),
                ('sample_size', models.PositiveIntegerField(default=10, help_text='Number of birds weighed for this average.')),
                ('average_weight_g', models.PositiveIntegerField(help_text='Average live weight in grams.')),
                ('notes', models.TextField(blank=True, default='')),
                ('reported_by_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_samples', to='poultry.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_weight_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sampled_at'],
            },
        ),
    ]
