# Generated by Django 6.0.6 on 2026-08-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0027_batch_broiler_strain_batchweightsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, help_text='Optional collection due date for credit sales.', null=True),
        ),
    ]
