# Generated by Django 6.0.6 on 2026-09-24 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_customer_customercostattribution_and_more'),
        ('poultry', '0032_sales_receivable_follow_up_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Stable customer identity. Buyer name remains the sale-time display record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='finance.customer'),
        ),
    ]
