# Generated by Django 6.0.6 on 2026-09-25 07:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0033_sales_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleSellingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('packaging', 'Packaging'), ('commission', 'Commission'), ('market_fee', 'Market fee'), ('other', 'Other selling cost')], db_index=True, default='transport', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sale_selling_costs', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_costs', to='poultry.sales')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['sale', 'category'], name='poultry_sal_sale_id_a4427b_idx')],
            },
        ),
    ]
