name: farm_management

services:
  farm_backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: farm_backend
    command: sh -c "python backend/manage.py migrate && python backend/manage.py runserver 0.0.0.0:7070"
    env_file:
      - ../.env
    volumes:
      - ..:/app

    ports:
      - "7070:7070"
    environment:
      DB_ENGINE: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_SSLMODE: disable
      POSTGRES_CONNECT_TIMEOUT: 5
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: farm_postgres_db
    env_file:
      - ../.env
    ports:
      - "5437:5432"
    volumes:
      - farm_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  farm_postgres_data:
