# Generated by Django 6.0.6 on 2026-07-17 09:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poultry', '0023_batch_closed_at_batch_closure_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_accounting_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='BatchProfitabilitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash_collected', models.DecimalField(decimal_places=2, max_digits=14)),
                ('accounts_receivable', models.DecimalField(decimal_places=2, max_digits=14)),
                ('direct_batch_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('allocated_production_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_production_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('batch_gross_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fully_loaded_batch_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valid_bird_units_sold', models.PositiveIntegerField(default=0)),
                ('remaining_live_birds', models.PositiveIntegerField(default=0)),
                ('final', models.BooleanField(db_index=True, default=False)),
                ('calculation_version', models.CharField(default='profitability-v1', max_length=40)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('accounting_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_profitability_snapshots', to='finance.accountingperiod')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profitability_snapshots', to='poultry.batch')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_profitability_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BirdDaySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_days', models.PositiveIntegerField(default=0)),
                ('opening_live_birds', models.PositiveIntegerField(default=0)),
                ('mortality', models.PositiveIntegerField(default=0)),
                ('valid_bird_units_sold', models.PositiveIntegerField(default=0)),
                ('closing_live_birds', models.PositiveIntegerField(default=0)),
                ('bird_days', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('calculation_version', models.CharField(default='bird-days-v1', max_length=40)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bird_day_snapshots', to='finance.accountingperiod')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bird_day_snapshots', to='poultry.batch')),
            ],
            options={
                'ordering': ['accounting_period', 'batch'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_number', models.CharField(max_length=40, unique=True)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('temporary', 'Temporary')], db_index=True, default='permanent', max_length=20)),
                ('job_title', models.CharField(max_length=120)),
                ('department', models.CharField(blank=True, default='', max_length=120)),
                ('employment_start_date', models.DateField()),
                ('employment_end_date', models.DateField(blank=True, null=True)),
                ('base_monthly_salary', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('standard_working_hours_per_day', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('standard_working_days_per_week', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('production_percentage', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('administration_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('selling_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_number'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBatchWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField(db_index=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('task', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_employee_batch_work_logs', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_work_logs', to='poultry.batch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_work_logs', to='finance.employeeprofile')),
            ],
            options={
                'ordering': ['-work_date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='AdHocLabourPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker_name', models.CharField(max_length=160)),
                ('task_description', models.CharField(max_length=255)),
                ('work_date', models.DateField(db_index=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cost_scope', models.CharField(choices=[('batch_direct', 'Batch direct'), ('shared_production', 'Shared production'), ('farm_administration', 'Farm administration'), ('selling_and_distribution', 'Selling and distribution')], db_index=True, max_length=40)),
                ('payment_date', models.DateField(blank=True, db_index=True, null=True)),
                ('payment_method', models.CharField(blank=True, default='', max_length=80)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled')], db_index=True, default='unpaid', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('accounting_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ad_hoc_labour_payments', to='finance.accountingperiod')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ad_hoc_labour_payments', to='poultry.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ad_hoc_labour_payments', to=settings.AUTH_USER_MODEL)),
                ('linked_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ad_hoc_labour_payments', to='finance.employeeprofile')),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('employer_costs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_employer_cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('production_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('administration_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('selling_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled')], db_index=True, default='unpaid', max_length=20)),
                ('payment_date', models.DateField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='finance.accountingperiod')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_entries', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='finance.employeeprofile')),
            ],
            options={
                'ordering': ['accounting_period', 'employee__employee_number'],
            },
        ),
        migrations.CreateModel(
            name='SharedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=120)),
                ('expense_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('scope', models.CharField(choices=[('shared_production', 'Shared production'), ('admin_overhead', 'Admin overhead'), ('selling_expense', 'Selling expense'), ('finance_cost', 'Finance cost'), ('capital_expenditure', 'Capital expenditure'), ('tax', 'Tax'), ('other', 'Other')], db_index=True, max_length=40)),
                ('allocation_method', models.CharField(choices=[('direct', 'Direct'), ('actual_hours', 'Actual hours'), ('bird_days', 'Bird-days'), ('revenue_share', 'Revenue share'), ('sales_quantity', 'Sales quantity'), ('manual', 'Manual'), ('none', 'None')], default='none', max_length=40)),
                ('payment_date', models.DateField(blank=True, db_index=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled')], db_index=True, default='unpaid', max_length=20)),
                ('supplier', models.CharField(blank=True, default='', max_length=160)),
                ('reference_number', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_expenses', to='finance.accountingperiod')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shared_expenses', to=settings.AUTH_USER_MODEL)),
                ('directly_assigned_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shared_expenses', to='poultry.batch')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('payroll', 'Payroll'), ('ad_hoc_labour', 'Ad-hoc labour'), ('shared_expense', 'Shared expense')], max_length=30)),
                ('allocation_method', models.CharField(choices=[('direct', 'Direct'), ('actual_hours', 'Actual hours'), ('bird_days', 'Bird-days'), ('revenue_share', 'Revenue share'), ('sales_quantity', 'Sales quantity'), ('manual', 'Manual'), ('none', 'None')], max_length=40)),
                ('driver_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_driver_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('allocation_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('calculation_version', models.CharField(default='allocation-v1', max_length=40)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('manual_reason', models.TextField(blank=True, default='')),
                ('locked', models.BooleanField(db_index=True, default=False)),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_allocations', to='finance.accountingperiod')),
                ('ad_hoc_labour_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_allocations', to='finance.adhoclabourpayment')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_allocations', to='poultry.batch')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_cost_allocations', to=settings.AUTH_USER_MODEL)),
                ('payroll_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_allocations', to='finance.payrollentry')),
                ('shared_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_allocations', to='finance.sharedexpense')),
            ],
            options={
                'ordering': ['accounting_period', 'batch', 'source_type'],
            },
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['period_start', 'period_end'], name='finance_acc_period__db18f5_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['status', 'period_start'], name='finance_acc_status_8744eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.UniqueConstraint(fields=('period_start', 'period_end'), name='unique_accounting_period_dates'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='accounting_period_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='batchprofitabilitysnapshot',
            index=models.Index(fields=['batch', 'final'], name='finance_bat_batch_i_16c666_idx'),
        ),
        migrations.AddIndex(
            model_name='batchprofitabilitysnapshot',
            index=models.Index(fields=['accounting_period', 'final'], name='finance_bat_account_f84daa_idx'),
        ),
        migrations.AddConstraint(
            model_name='batchprofitabilitysnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('final', True)), fields=('batch',), name='unique_final_profitability_snapshot_per_batch'),
        ),
        migrations.AddIndex(
            model_name='birddaysnapshot',
            index=models.Index(fields=['accounting_period', 'batch'], name='finance_bir_account_54c0a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='birddaysnapshot',
            constraint=models.UniqueConstraint(fields=('accounting_period', 'batch', 'calculation_version'), name='unique_bird_day_snapshot_period_batch_version'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['employment_type', 'is_active'], name='finance_emp_employm_265877_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['employment_start_date', 'employment_end_date'], name='finance_emp_employm_07c62d_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebatchworklog',
            index=models.Index(fields=['employee', 'work_date'], name='finance_emp_employe_f7a864_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebatchworklog',
            index=models.Index(fields=['batch', 'work_date'], name='finance_emp_batch_i_2e8383_idx'),
        ),
        migrations.AddIndex(
            model_name='adhoclabourpayment',
            index=models.Index(fields=['accounting_period', 'cost_scope'], name='finance_adh_account_d6824d_idx'),
        ),
        migrations.AddIndex(
            model_name='adhoclabourpayment',
            index=models.Index(fields=['batch', 'cost_scope'], name='finance_adh_batch_i_6050fc_idx'),
        ),
        migrations.AddIndex(
            model_name='adhoclabourpayment',
            index=models.Index(fields=['payment_status', 'payment_date'], name='finance_adh_payment_aa3356_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollentry',
            index=models.Index(fields=['accounting_period', 'employee'], name='finance_pay_account_e669a0_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollentry',
            index=models.Index(fields=['payment_status', 'payment_date'], name='finance_pay_payment_98afb3_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollentry',
            constraint=models.UniqueConstraint(fields=('accounting_period', 'employee'), name='unique_payroll_entry_per_employee_period'),
        ),
        migrations.AddIndex(
            model_name='sharedexpense',
            index=models.Index(fields=['accounting_period', 'scope'], name='finance_sha_account_9d6c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedexpense',
            index=models.Index(fields=['directly_assigned_batch', 'scope'], name='finance_sha_directl_c16e62_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedexpense',
            index=models.Index(fields=['payment_status', 'payment_date'], name='finance_sha_payment_faa9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedexpense',
            index=models.Index(fields=['expense_date'], name='finance_sha_expense_eb1876_idx'),
        ),
        migrations.AddIndex(
            model_name='costallocation',
            index=models.Index(fields=['accounting_period', 'batch'], name='finance_cos_account_d862f9_idx'),
        ),
        migrations.AddIndex(
            model_name='costallocation',
            index=models.Index(fields=['source_type', 'allocation_method'], name='finance_cos_source__afa737_idx'),
        ),
        migrations.AddIndex(
            model_name='costallocation',
            index=models.Index(fields=['locked'], name='finance_cos_locked_cc4488_idx'),
        ),
        migrations.AddConstraint(
            model_name='costallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payroll_entry__isnull', False), ('ad_hoc_labour_payment__isnull', True), ('shared_expense__isnull', True)), models.Q(('payroll_entry__isnull', True), ('ad_hoc_labour_payment__isnull', False), ('shared_expense__isnull', True)), models.Q(('payroll_entry__isnull', True), ('ad_hoc_labour_payment__isnull', True), ('shared_expense__isnull', False)), _connector='OR'), name='cost_allocation_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='costallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('payroll_entry__isnull', False)), fields=('accounting_period', 'batch', 'payroll_entry'), name='unique_payroll_allocation_period_batch'),
        ),
        migrations.AddConstraint(
            model_name='costallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('ad_hoc_labour_payment__isnull', False)), fields=('accounting_period', 'batch', 'ad_hoc_labour_payment'), name='unique_labour_allocation_period_batch'),
        ),
        migrations.AddConstraint(
            model_name='costallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('shared_expense__isnull', False)), fields=('accounting_period', 'batch', 'shared_expense'), name='unique_expense_allocation_period_batch'),
        ),
    ]
