# Generated by Django 6.0.6 on 2026-07-24 19:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_accounting_period_year_month(apps, schema_editor):
    AccountingPeriod = apps.get_model('finance', 'AccountingPeriod')
    for period in AccountingPeriod.objects.all():
        period.year = period.period_start.year
        period.month = period.period_start.month
        period.save(update_fields=['year', 'month'])


def seed_asset_categories(apps, schema_editor):
    AssetCategory = apps.get_model('finance', 'AssetCategory')
    defaults = [
        ('Poultry House', 'poultry_house', 120, 'poultry_production', 'bird_days'),
        ('Feeding Equipment', 'feeding_equipment', 60, 'poultry_production', 'bird_days'),
        ('Watering Equipment', 'watering_equipment', 60, 'poultry_production', 'bird_days'),
        ('Brooding Equipment', 'brooding_equipment', 48, 'poultry_production', 'bird_days'),
        ('Water Infrastructure', 'water_infrastructure', 96, 'poultry_production', 'house_occupancy_days'),
        ('Processing Equipment', 'processing_equipment', 84, 'poultry_production', 'sales_quantity'),
        ('Cold Storage', 'cold_storage', 84, 'mixed_use', 'equal_share'),
        ('Solar Equipment', 'solar_equipment', 120, 'mixed_use', 'equal_share'),
        ('Vehicle', 'vehicle', 60, 'selling_and_distribution', 'revenue_share'),
        ('Office Equipment', 'office_equipment', 48, 'farm_administration', 'none'),
        ('Other', 'other', 60, 'mixed_use', 'equal_share'),
    ]
    for name, code, useful_life, scope, driver in defaults:
        AssetCategory.objects.get_or_create(
            code=code,
            defaults={
                'name': name,
                'default_useful_life_months': useful_life,
                'default_residual_value_percentage': Decimal('0.00'),
                'default_depreciation_method': 'straight_line',
                'default_production_scope': scope,
                'default_allocation_driver': driver,
                'capitalization_threshold': Decimal('0.00'),
                'requires_serial_number': False,
                'is_active': True,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('poultry', '0024_batch_booking_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usd_exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='MWK per USD at entry time.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('usd_equivalent', models.DecimalField(blank=True, decimal_places=2, help_text='USD equivalent captured for future inflation reference.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(blank=True, db_index=True, max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('category_other', models.CharField(blank=True, default='', max_length=120)),
                ('serial_number', models.CharField(blank=True, default='', max_length=120)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=120)),
                ('model_number', models.CharField(blank=True, default='', max_length=120)),
                ('supplier', models.CharField(blank=True, default='', max_length=160)),
                ('invoice_reference', models.CharField(blank=True, default='', max_length=120)),
                ('purchase_date', models.DateField(db_index=True)),
                ('available_for_use_date', models.DateField(blank=True, db_index=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('installation_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('non_refundable_tax_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('other_capitalized_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_capitalized_cost', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('residual_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('recognized_impairment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('useful_life_months', models.PositiveIntegerField()),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight line'), ('units_of_production', 'Units of production'), ('declining_balance', 'Declining balance')], default='straight_line', max_length=40)),
                ('depreciation_unit', models.CharField(blank=True, default='', max_length=40)),
                ('estimated_total_lifetime_units', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('production_scope', models.CharField(choices=[('poultry_production', 'Poultry production'), ('selling_and_distribution', 'Selling and distribution'), ('farm_administration', 'Farm administration'), ('mixed_use', 'Mixed use')], db_index=True, default='poultry_production', max_length=40)),
                ('production_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('administration_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('selling_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('default_allocation_driver', models.CharField(choices=[('direct', 'Direct'), ('actual_hours', 'Actual hours'), ('bird_days', 'Bird-days'), ('batch_days', 'Batch-days'), ('house_occupancy_days', 'House occupancy days'), ('floor_area_days', 'Floor-area days'), ('equal_share', 'Equal share'), ('revenue_share', 'Revenue share'), ('sales_quantity', 'Sales quantity'), ('actual_quantity', 'Actual quantity'), ('manual_with_reason', 'Manual with reason'), ('manual', 'Manual'), ('none', 'None')], default='bird_days', max_length=40)),
                ('fallback_allocation_driver', models.CharField(choices=[('direct', 'Direct'), ('actual_hours', 'Actual hours'), ('bird_days', 'Bird-days'), ('batch_days', 'Batch-days'), ('house_occupancy_days', 'House occupancy days'), ('floor_area_days', 'Floor-area days'), ('equal_share', 'Equal share'), ('revenue_share', 'Revenue share'), ('sales_quantity', 'Sales quantity'), ('actual_quantity', 'Actual quantity'), ('manual_with_reason', 'Manual with reason'), ('manual', 'Manual'), ('none', 'None')], default='equal_share', max_length=40)),
                ('location', models.CharField(blank=True, default='', max_length=160)),
                ('custodian', models.CharField(blank=True, default='', max_length=160)),
                ('condition', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('available_for_use', 'Available for use'), ('idle', 'Idle'), ('under_maintenance', 'Under maintenance'), ('impaired', 'Impaired'), ('disposed', 'Disposed'), ('retired', 'Retired')], db_index=True, default='draft', max_length=40)),
                ('warranty_expiry_date', models.DateField(blank=True, null=True)),
                ('financing_type', models.CharField(blank=True, default='', max_length=80)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_proceeds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('disposal_gain_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['asset_code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetCapitalizedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usd_exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='MWK per USD at entry time.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('usd_equivalent', models.DecimalField(blank=True, decimal_places=2, help_text='USD equivalent captured for future inflation reference.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('capitalized_amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['asset', 'expense'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(choices=[('poultry_house', 'Poultry house'), ('feeding_equipment', 'Feeding equipment'), ('watering_equipment', 'Watering equipment'), ('brooding_equipment', 'Brooding equipment'), ('water_infrastructure', 'Water infrastructure'), ('processing_equipment', 'Processing equipment'), ('cold_storage', 'Cold storage'), ('solar_equipment', 'Solar equipment'), ('vehicle', 'Vehicle'), ('office_equipment', 'Office equipment'), ('other', 'Other')], max_length=40, unique=True)),
                ('default_useful_life_months', models.PositiveIntegerField()),
                ('default_residual_value_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('default_depreciation_method', models.CharField(choices=[('straight_line', 'Straight line'), ('units_of_production', 'Units of production'), ('declining_balance', 'Declining balance')], default='straight_line', max_length=40)),
                ('default_production_scope', models.CharField(choices=[('poultry_production', 'Poultry production'), ('selling_and_distribution', 'Selling and distribution'), ('farm_administration', 'Farm administration'), ('mixed_use', 'Mixed use')], default='poultry_production', max_length=40)),
                ('default_allocation_driver', models.CharField(choices=[('direct', 'Direct'), ('actual_hours', 'Actual hours'), ('bird_days', 'Bird-days'), ('batch_days', 'Batch-days'), ('house_occupancy_days', 'House occupancy days'), ('floor_area_days', 'Floor-area days'), ('equal_share', 'Equal share'), ('revenue_share', 'Revenue share'), ('sales_quantity', 'Sales quantity'), ('actual_quantity', 'Actual quantity'), ('manual_with_reason', 'Manual with reason'), ('manual', 'Manual'), ('none', 'None')], default='bird_days', max_length=40)),
                ('capitalization_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('requires_serial_number', models.BooleanField(default=False)),
                ('maintenance_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usd_exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='MWK per USD at entry time.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('usd_equivalent', models.DecimalField(blank=True, decimal_places=2, help_text='USD equivalent captured for future inflation reference.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('opening_carrying_amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('depreciation_method_snapshot', models.CharField(max_length=40)),
                ('useful_life_snapshot', models.PositiveIntegerField()),
                ('residual_value_snapshot', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('period_depreciation', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('impairment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('closing_carrying_amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('calculation_version', models.CharField(default='depreciation-v1', max_length=40)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['accounting_period', 'asset'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usd_exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='MWK per USD at entry time.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('usd_equivalent', models.DecimalField(blank=True, decimal_places=2, help_text='USD equivalent captured for future inflation reference.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('maintenance_date', models.DateField(db_index=True)),
                ('description', models.CharField(max_length=255)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('next_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-maintenance_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetReplacementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usd_exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='MWK per USD at entry time.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('usd_equivalent', models.DecimalField(blank=True, decimal_places=2, help_text='USD equivalent captured for future inflation reference.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_replacement_cost', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('annual_inflation_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('target_replacement_date', models.DateField()),
                ('projected_future_replacement_cost', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('target_reserve_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['asset'],
            },
        ),
        migrations.CreateModel(
            name='AssetUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_date', models.DateField(db_index=True)),
                ('usage_unit', models.CharField(max_length=40)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('meter_opening', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('meter_closing', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, default='')),
                ('locked', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-usage_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_date', models.DateField(db_index=True)),
                ('quantity_used', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('poultry_house', models.CharField(blank=True, default='', max_length=120)),
                ('usage_scope', models.CharField(choices=[('batch_direct', 'Batch direct'), ('shared_production', 'Shared production'), ('administration', 'Administration'), ('selling_and_distribution', 'Selling and distribution')], db_index=True, max_length=40)),
                ('allocation_driver', models.CharField(choices=[('direct', 'Direct'), ('actual_hours', 'Actual hours'), ('bird_days', 'Bird-days'), ('batch_days', 'Batch-days'), ('house_occupancy_days', 'House occupancy days'), ('floor_area_days', 'Floor-area days'), ('equal_share', 'Equal share'), ('revenue_share', 'Revenue share'), ('sales_quantity', 'Sales quantity'), ('actual_quantity', 'Actual quantity'), ('manual_with_reason', 'Manual with reason'), ('manual', 'Manual'), ('none', 'None')], default='none', max_length=40)),
                ('task_or_purpose', models.CharField(max_length=255)),
                ('recognized_cost', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, default='')),
                ('locked', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-usage_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseRecognitionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usd_exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='MWK per USD at entry time.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('usd_equivalent', models.DecimalField(blank=True, decimal_places=2, help_text='USD equivalent captured for future inflation reference.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('benefit_start_date', models.DateField()),
                ('benefit_end_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('recognition_method', models.CharField(choices=[('straight_line', 'Straight line'), ('usage_based', 'Usage based'), ('manual_schedule', 'Manual schedule')], default='straight_line', max_length=40)),
                ('amount_recognized', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remaining_deferred_amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['accounting_period', 'source_expense'],
            },
        ),
        migrations.CreateModel(
            name='ReplacementReserveTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usd_exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='MWK per USD at entry time.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('usd_equivalent', models.DecimalField(blank=True, decimal_places=2, help_text='USD equivalent captured for future inflation reference.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('transaction_date', models.DateField(db_index=True)),
                ('transaction_type', models.CharField(choices=[('contribution', 'Contribution'), ('withdrawal', 'Withdrawal'), ('return', 'Investment return')], db_index=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedConsumableLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usd_exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='MWK per USD at entry time.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('usd_equivalent', models.DecimalField(blank=True, decimal_places=2, help_text='USD equivalent captured for future inflation reference.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('item', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=120)),
                ('purchase_date', models.DateField(db_index=True)),
                ('supplier', models.CharField(blank=True, default='', max_length=160)),
                ('invoice_reference', models.CharField(blank=True, default='', max_length=120)),
                ('quantity_purchased', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_of_measurement', models.CharField(max_length=40)),
                ('total_purchase_cost', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('storage_location', models.CharField(blank=True, default='', max_length=160)),
                ('quantity_available', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled')], db_index=True, default='unpaid', max_length=20)),
                ('payment_date', models.DateField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['item', 'purchase_date'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='costallocation',
            name='cost_allocation_exactly_one_source',
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='recalculation_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_accounting_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='reopening_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='adhoclabourpayment',
            name='usd_equivalent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='USD equivalent captured for future inflation reference.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='adhoclabourpayment',
            name='usd_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='MWK per USD at entry time.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='usd_equivalent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='USD equivalent captured for future inflation reference.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='usd_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='MWK per USD at entry time.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='usd_equivalent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='USD equivalent captured for future inflation reference.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='usd_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='MWK per USD at entry time.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AddField(
            model_name='sharedexpense',
            name='recognition_type',
            field=models.CharField(choices=[('operating_expense', 'Operating expense'), ('capital_expenditure', 'Capital expenditure'), ('prepaid_expense', 'Prepaid expense'), ('shared_consumable', 'Shared consumable'), ('finance_cost', 'Finance cost'), ('tax', 'Tax'), ('other', 'Other')], db_index=True, default='operating_expense', max_length=40),
        ),
        migrations.AddField(
            model_name='sharedexpense',
            name='usd_equivalent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='USD equivalent captured for future inflation reference.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='sharedexpense',
            name='usd_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='MWK per USD at entry time.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='allocation_method',
            field=models.CharField(choices=[('direct', 'Direct'), ('actual_hours', 'Actual hours'), ('bird_days', 'Bird-days'), ('batch_days', 'Batch-days'), ('house_occupancy_days', 'House occupancy days'), ('floor_area_days', 'Floor-area days'), ('equal_share', 'Equal share'), ('revenue_share', 'Revenue share'), ('sales_quantity', 'Sales quantity'), ('actual_quantity', 'Actual quantity'), ('manual_with_reason', 'Manual with reason'), ('manual', 'Manual'), ('none', 'None')], max_length=40),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='source_type',
            field=models.CharField(choices=[('payroll', 'Payroll'), ('ad_hoc_labour', 'Ad-hoc labour'), ('shared_expense', 'Shared expense'), ('consumable_usage', 'Consumable usage'), ('depreciation', 'Depreciation')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sharedexpense',
            name='allocation_method',
            field=models.CharField(choices=[('direct', 'Direct'), ('actual_hours', 'Actual hours'), ('bird_days', 'Bird-days'), ('batch_days', 'Batch-days'), ('house_occupancy_days', 'House occupancy days'), ('floor_area_days', 'Floor-area days'), ('equal_share', 'Equal share'), ('revenue_share', 'Revenue share'), ('sales_quantity', 'Sales quantity'), ('actual_quantity', 'Actual quantity'), ('manual_with_reason', 'Manual with reason'), ('manual', 'Manual'), ('none', 'None')], default='none', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('month__isnull', True), models.Q(('month__gte', 1), ('month__lte', 12)), _connector='OR'), name='accounting_period_valid_month'),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetcapitalizedcost',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capitalized_cost_links', to='finance.asset'),
        ),
        migrations.AddField(
            model_name='assetcapitalizedcost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_capitalized_costs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetcapitalizedcost',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capitalized_asset_links', to='finance.sharedexpense'),
        ),
        migrations.AddIndex(
            model_name='assetcategory',
            index=models.Index(fields=['code', 'is_active'], name='finance_ass_code_938d6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.CheckConstraint(condition=models.Q(('default_residual_value_percentage__gte', 0), ('default_residual_value_percentage__lte', 100)), name='asset_category_residual_percentage_valid'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='finance.assetcategory'),
        ),
        migrations.AddField(
            model_name='assetdepreciationentry',
            name='accounting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_depreciation_entries', to='finance.accountingperiod'),
        ),
        migrations.AddField(
            model_name='assetdepreciationentry',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_entries', to='finance.asset'),
        ),
        migrations.AddField(
            model_name='assetdepreciationentry',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_asset_depreciation_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costallocation',
            name='depreciation_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_allocations', to='finance.assetdepreciationentry'),
        ),
        migrations.AddField(
            model_name='assetmaintenancerecord',
            name='accounting_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_maintenance_records', to='finance.accountingperiod'),
        ),
        migrations.AddField(
            model_name='assetmaintenancerecord',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='finance.asset'),
        ),
        migrations.AddField(
            model_name='assetmaintenancerecord',
            name='linked_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_maintenance_records', to='finance.sharedexpense'),
        ),
        migrations.AddField(
            model_name='assetmaintenancerecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_asset_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetreplacementplan',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='replacement_plan', to='finance.asset'),
        ),
        migrations.AddField(
            model_name='assetreplacementplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_asset_replacement_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetusagerecord',
            name='accounting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_usage_records', to='finance.accountingperiod'),
        ),
        migrations.AddField(
            model_name='assetusagerecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_asset_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetusagerecord',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='finance.asset'),
        ),
        migrations.AddField(
            model_name='assetusagerecord',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_usage_records', to='poultry.batch'),
        ),
        migrations.AddField(
            model_name='assetusagerecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_asset_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumableusage',
            name='accounting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumable_usages', to='finance.accountingperiod'),
        ),
        migrations.AddField(
            model_name='consumableusage',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_consumable_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumableusage',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumable_usages', to='poultry.batch'),
        ),
        migrations.AddField(
            model_name='consumableusage',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_consumable_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costallocation',
            name='consumable_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_allocations', to='finance.consumableusage'),
        ),
        migrations.AddConstraint(
            model_name='costallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payroll_entry__isnull', False), ('ad_hoc_labour_payment__isnull', True), ('shared_expense__isnull', True), ('consumable_usage__isnull', True), ('depreciation_entry__isnull', True)), models.Q(('payroll_entry__isnull', True), ('ad_hoc_labour_payment__isnull', False), ('shared_expense__isnull', True), ('consumable_usage__isnull', True), ('depreciation_entry__isnull', True)), models.Q(('payroll_entry__isnull', True), ('ad_hoc_labour_payment__isnull', True), ('shared_expense__isnull', False), ('consumable_usage__isnull', True), ('depreciation_entry__isnull', True)), models.Q(('payroll_entry__isnull', True), ('ad_hoc_labour_payment__isnull', True), ('shared_expense__isnull', True), ('consumable_usage__isnull', False), ('depreciation_entry__isnull', True)), models.Q(('payroll_entry__isnull', True), ('ad_hoc_labour_payment__isnull', True), ('shared_expense__isnull', True), ('consumable_usage__isnull', True), ('depreciation_entry__isnull', False)), _connector='OR'), name='cost_allocation_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='costallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('consumable_usage__isnull', False)), fields=('accounting_period', 'batch', 'consumable_usage'), name='unique_consumable_allocation_period_batch'),
        ),
        migrations.AddConstraint(
            model_name='costallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('depreciation_entry__isnull', False)), fields=('accounting_period', 'batch', 'depreciation_entry'), name='unique_depreciation_allocation_period_batch'),
        ),
        migrations.AddField(
            model_name='expenserecognitionschedule',
            name='accounting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_recognition_schedules', to='finance.accountingperiod'),
        ),
        migrations.AddField(
            model_name='expenserecognitionschedule',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_expense_recognition_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenserecognitionschedule',
            name='source_expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recognition_schedules', to='finance.sharedexpense'),
        ),
        migrations.AddField(
            model_name='replacementreservetransaction',
            name='accounting_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_reserve_transactions', to='finance.accountingperiod'),
        ),
        migrations.AddField(
            model_name='replacementreservetransaction',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserve_transactions', to='finance.asset'),
        ),
        migrations.AddField(
            model_name='replacementreservetransaction',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_replacement_reserve_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedconsumablelot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consumable_lots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedconsumablelot',
            name='linked_expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumable_lot', to='finance.sharedexpense'),
        ),
        migrations.AddField(
            model_name='consumableusage',
            name='consumable_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='finance.sharedconsumablelot'),
        ),
        migrations.AddConstraint(
            model_name='assetcapitalizedcost',
            constraint=models.UniqueConstraint(fields=('asset', 'expense'), name='unique_asset_capitalized_expense_link'),
        ),
        migrations.AddConstraint(
            model_name='assetcapitalizedcost',
            constraint=models.CheckConstraint(condition=models.Q(('capitalized_amount__gte', 0)), name='asset_capitalized_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status', 'production_scope'], name='finance_ass_status_30ac9a_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['purchase_date', 'available_for_use_date'], name='finance_ass_purchas_ad780f_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_category', 'status'], name='finance_ass_asset_c_6c538d_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('total_capitalized_cost__gt', 0)), name='asset_total_capitalized_cost_positive'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('residual_value__gte', 0)), name='asset_residual_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('residual_value__lte', models.F('total_capitalized_cost'))), name='asset_residual_not_above_cost'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('production_percentage__gte', 0), ('production_percentage__lte', 100), ('administration_percentage__gte', 0), ('administration_percentage__lte', 100), ('selling_percentage__gte', 0), ('selling_percentage__lte', 100)), name='asset_percentages_between_zero_and_hundred'),
        ),
        migrations.AddIndex(
            model_name='assetdepreciationentry',
            index=models.Index(fields=['accounting_period', 'locked'], name='finance_ass_account_ac9300_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdepreciationentry',
            index=models.Index(fields=['asset', 'accounting_period'], name='finance_ass_asset_i_7b2f50_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetdepreciationentry',
            constraint=models.UniqueConstraint(fields=('asset', 'accounting_period'), name='unique_asset_depreciation_entry_per_period'),
        ),
        migrations.AddConstraint(
            model_name='assetdepreciationentry',
            constraint=models.CheckConstraint(condition=models.Q(('period_depreciation__gte', 0)), name='asset_period_depreciation_non_negative'),
        ),
        migrations.AddIndex(
            model_name='assetmaintenancerecord',
            index=models.Index(fields=['asset', 'maintenance_date'], name='finance_ass_asset_i_4b2f29_idx'),
        ),
        migrations.AddIndex(
            model_name='assetmaintenancerecord',
            index=models.Index(fields=['next_due_date'], name='finance_ass_next_du_b9a525_idx'),
        ),
        migrations.AddIndex(
            model_name='assetusagerecord',
            index=models.Index(fields=['asset', 'accounting_period'], name='finance_ass_asset_i_4bf17f_idx'),
        ),
        migrations.AddIndex(
            model_name='assetusagerecord',
            index=models.Index(fields=['batch', 'usage_date'], name='finance_ass_batch_i_8aa822_idx'),
        ),
        migrations.AddIndex(
            model_name='assetusagerecord',
            index=models.Index(fields=['locked'], name='finance_ass_locked_e130dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetusagerecord',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='asset_usage_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='expenserecognitionschedule',
            index=models.Index(fields=['accounting_period', 'locked'], name='finance_exp_account_0f5a42_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserecognitionschedule',
            index=models.Index(fields=['source_expense', 'accounting_period'], name='finance_exp_source__d955de_idx'),
        ),
        migrations.AddConstraint(
            model_name='expenserecognitionschedule',
            constraint=models.UniqueConstraint(fields=('source_expense', 'accounting_period'), name='unique_expense_recognition_per_period'),
        ),
        migrations.AddConstraint(
            model_name='expenserecognitionschedule',
            constraint=models.CheckConstraint(condition=models.Q(('benefit_end_date__gte', models.F('benefit_start_date'))), name='expense_recognition_benefit_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='replacementreservetransaction',
            index=models.Index(fields=['asset', 'transaction_date'], name='finance_rep_asset_i_9e4e69_idx'),
        ),
        migrations.AddIndex(
            model_name='replacementreservetransaction',
            index=models.Index(fields=['transaction_type', 'transaction_date'], name='finance_rep_transac_ffbea3_idx'),
        ),
        migrations.AddConstraint(
            model_name='replacementreservetransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='replacement_reserve_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='sharedconsumablelot',
            index=models.Index(fields=['category', 'purchase_date'], name='finance_sha_categor_4a13f2_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedconsumablelot',
            index=models.Index(fields=['expiry_date'], name='finance_sha_expiry__5f743e_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedconsumablelot',
            index=models.Index(fields=['payment_status', 'payment_date'], name='finance_sha_payment_29dd2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='sharedconsumablelot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_purchased__gt', 0)), name='consumable_quantity_purchased_positive'),
        ),
        migrations.AddConstraint(
            model_name='sharedconsumablelot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_available__gte', 0)), name='consumable_quantity_available_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sharedconsumablelot',
            constraint=models.CheckConstraint(condition=models.Q(('total_purchase_cost__gte', 0)), name='consumable_purchase_cost_non_negative'),
        ),
        migrations.AddIndex(
            model_name='consumableusage',
            index=models.Index(fields=['accounting_period', 'usage_scope'], name='finance_con_account_ba7059_idx'),
        ),
        migrations.AddIndex(
            model_name='consumableusage',
            index=models.Index(fields=['batch', 'usage_scope'], name='finance_con_batch_i_582683_idx'),
        ),
        migrations.AddIndex(
            model_name='consumableusage',
            index=models.Index(fields=['locked'], name='finance_con_locked_f95632_idx'),
        ),
        migrations.AddConstraint(
            model_name='consumableusage',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_used__gt', 0)), name='consumable_usage_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='consumableusage',
            constraint=models.CheckConstraint(condition=models.Q(('recognized_cost__gte', 0)), name='consumable_usage_cost_non_negative'),
        ),
        migrations.RunPython(backfill_accounting_period_year_month, noop_reverse),
        migrations.RunPython(seed_asset_categories, noop_reverse),
    ]
