# Generated by Django 6.0.6 on 2026-07-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_asset_assetcapitalizedcost_assetcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='code',
            field=models.CharField(choices=[('poultry_house', 'Poultry house'), ('feeding_equipment', 'Feeding equipment'), ('watering_equipment', 'Watering equipment'), ('brooding_equipment', 'Brooding equipment'), ('water_infrastructure', 'Water infrastructure'), ('processing_equipment', 'Processing equipment'), ('cold_storage', 'Cold storage'), ('solar_equipment', 'Solar equipment'), ('vehicle', 'Vehicle'), ('office_equipment', 'Office equipment'), ('other', 'Other')], max_length=40),
        ),
    ]
