# Generated by Django 6.0.6 on 2026-08-25 14:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_seed_expenditure_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('default_accounting_nature', models.CharField(choices=[('direct_cost', 'Direct Cost'), ('indirect_operating_expense', 'Indirect Operating Expense'), ('capital_expenditure', 'Capital Expenditure'), ('loan_repayment', 'Loan Repayment'), ('owner_withdrawal', 'Owner Withdrawal'), ('transfer', 'Transfer'), ('other', 'Other')], default='other', max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='expenditure',
            new_name='finance_exp_status_7e677e_idx',
            old_name='finance_exp_status__e0e0e0_idx',
        ),
        migrations.RenameIndex(
            model_name='expenditure',
            new_name='finance_exp_account_022b7d_idx',
            old_name='finance_exp_account_e0e0e0_idx',
        ),
        migrations.RenameIndex(
            model_name='expenditure',
            new_name='finance_exp_account_db31c7_idx',
            old_name='finance_exp_account_e1e1e1_idx',
        ),
        migrations.RenameIndex(
            model_name='fundingallocation',
            new_name='finance_fun_expendi_aad50f_idx',
            old_name='finance_fun_expendi_e0e0e0_idx',
        ),
        migrations.RenameIndex(
            model_name='fundingallocation',
            new_name='finance_fun_funding_a6275f_idx',
            old_name='finance_fun_funding_e0e0e0_idx',
        ),
        migrations.RenameIndex(
            model_name='fundingsource',
            new_name='finance_fun_source__13b73a_idx',
            old_name='finance_fun_source__e0e0e0_idx',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='beneficiary_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='beneficiary_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='expenditure_reference',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='external_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='other_category_detail',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='reference_number',
            field=models.CharField(blank=True, default='', editable=False, max_length=120),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='usd_equivalent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='USD equivalent captured for future inflation reference.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='usd_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='MWK per USD at entry time.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AlterField(
            model_name='fundingallocation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenditures', to='finance.expenditurecategory'),
        ),
    ]
