# Generated by Django 6.0.6 on 2026-08-25 19:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_seed_expenditure_categories'),
        ('poultry', '0028_sales_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='cost_allocation_plan',
            field=models.JSONField(blank=True, default=list, help_text='Draft beneficiary allocation rows applied atomically when posted.'),
        ),
        migrations.CreateModel(
            name='FundingReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('receipt_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('reversed', 'Reversed')], db_index=True, default='posted', max_length=20)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_funding_receipts', to=settings.AUTH_USER_MODEL)),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='finance.fundingsource')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_funding_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-receipt_date', '-created_at'],
                'indexes': [models.Index(fields=['funding_source', 'status'], name='finance_fun_funding_6d3ea8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_reference', models.CharField(db_index=True, editable=False, max_length=40, unique=True)),
                ('idempotency_key', models.CharField(blank=True, editable=False, max_length=120, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payment_method', models.CharField(max_length=50)),
                ('external_reference', models.CharField(blank=True, default='', max_length=120)),
                ('received_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('reversed', 'Reversed')], db_index=True, default='posted', max_length=20)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sale_payments', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_sale_payments', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='poultry.sales')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['sale', 'status'], name='finance_sal_sale_id_4303c0_idx'), models.Index(fields=['payment_date', 'status'], name='finance_sal_payment_20c78a_idx')],
            },
        ),
    ]
