# Generated by Django 6.0.6 on 2026-09-01 07:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def expose_legacy_expenses_and_payroll(apps, schema_editor):
    Category = apps.get_model("finance", "ExpenditureCategory")
    Expenditure = apps.get_model("finance", "Expenditure")
    SharedExpense = apps.get_model("finance", "SharedExpense")
    PayrollEntry = apps.get_model("finance", "PayrollEntry")
    PayrollLiability = apps.get_model("finance", "PayrollLiability")

    legacy_category, _ = Category.objects.get_or_create(
        code="legacy_shared_expense",
        defaults={
            "name": "Legacy finance expense",
            "default_accounting_nature": "indirect_operating_expense",
            "display_order": 900,
        },
    )
    salary_category = Category.objects.filter(name="Salaries and wages").first()
    if salary_category is None:
        salary_category, _ = Category.objects.get_or_create(
            code="salaries",
            defaults={
                "name": "Salaries and wages",
                "default_accounting_nature": "indirect_operating_expense",
                "display_order": 25,
            },
        )
    for legacy in SharedExpense.objects.filter(expenditure__isnull=True).iterator():
        expenditure = Expenditure.objects.create(
            expenditure_date=legacy.expense_date,
            accounting_period_id=legacy.accounting_period_id,
            amount=legacy.amount,
            category=legacy_category,
            accounting_nature="indirect_operating_expense",
            description=legacy.description,
            payee=legacy.supplier,
            external_reference=legacy.reference_number,
            status="posted",
            payment_status=(
                "historical_unassigned"
                if legacy.payment_status in {"paid", "partial"}
                else "unpaid"
            ),
            origin="finance",
            beneficiary_type=("one_poultry_batch" if legacy.directly_assigned_batch_id else "legacy_scope"),
            beneficiary_detail=(str(legacy.directly_assigned_batch_id or legacy.scope)),
            expenditure_reference=f"LEGACY-SE-{legacy.pk:08d}",
            notes=legacy.notes,
            created_by_id=legacy.created_by_id,
        )
        legacy.expenditure_id = expenditure.pk
        legacy.save(update_fields=["expenditure"])

    for entry in PayrollEntry.objects.filter(expenditure__isnull=True).iterator():
        expenditure = Expenditure.objects.create(
            expenditure_date=entry.accounting_period.period_end,
            accounting_period_id=entry.accounting_period_id,
            amount=entry.total_employer_cost,
            category=salary_category,
            accounting_nature="indirect_operating_expense",
            description=f"Payroll cost: {entry.employee} ({entry.accounting_period})",
            status="posted",
            payment_status="historical_unassigned" if entry.payment_status in {"paid", "partial"} else "unpaid",
            origin="finance",
            beneficiary_type="payroll_allocation",
            expenditure_reference=f"LEGACY-PAY-{entry.pk:07d}",
            created_by_id=entry.created_by_id,
        )
        entry.expenditure_id = expenditure.pk
        entry.save(update_fields=["expenditure"])
        PayrollLiability.objects.create(
            payroll_entry=entry,
            amount=entry.deductions,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_ensure_complete_expenditure_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='cost_allocation_plan',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='expenditure',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entry', to='finance.expenditure'),
        ),
        migrations.AddField(
            model_name='sharedexpense',
            name='expenditure',
            field=models.OneToOneField(blank=True, help_text='Authoritative expenditure projection for this historical finance record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_shared_expense', to='finance.expenditure'),
        ),
        migrations.AlterField(
            model_name='adhoclabourpayment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='sharedconsumablelot',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='sharedexpense',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.CreateModel(
            name='PayrollLiability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remitted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.CharField(default='Employee deductions payable to statutory authority', max_length=160)),
                ('payroll_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deduction_liability', to='finance.payrollentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(db_index=True)),
                ('payment_method', models.CharField(max_length=80)),
                ('external_reference', models.CharField(blank=True, default='', max_length=120)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('reversed', 'Reversed')], db_index=True, default='posted', max_length=20)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, default='')),
                ('payroll_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.payrollentry')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_payroll_payments', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_payroll_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPaymentFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_allocations', to='finance.fundingsource')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funding_allocations', to='finance.payrollpayment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(expose_legacy_expenses_and_payroll, migrations.RunPython.noop),
    ]
