# Generated by Django 6.0.6 on 2026-09-03 14:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_seed_chart_and_reporting_policy'),
        ('poultry', '0030_dated_feed_population_and_arrival_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='adhoclabourpayment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adhoclabourpayment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ad_hoc_labour', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adhoclabourpayment',
            name='expenditure',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labour_source', to='finance.expenditure'),
        ),
        migrations.AddField(
            model_name='adhoclabourpayment',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adhoclabourpayment',
            name='reversal_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='adhoclabourpayment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adhoclabourpayment',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_ad_hoc_labour', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adhoclabourpayment',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('posted', 'Posted / payable'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('reversed', 'Reversed')], db_index=True, default='draft', max_length=24),
        ),
        migrations.CreateModel(
            name='ConsumableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=80)),
                ('base_unit', models.CharField(max_length=40)),
                ('costing_method', models.CharField(choices=[('weighted_average', 'Weighted average'), ('fifo', 'FIFO')], default='weighted_average', max_length=24)),
                ('reorder_level', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='finance_con_categor_a15c0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('acquisition', 'Acquisition'), ('available_for_use', 'Available for use'), ('capitalized_cost', 'Additional capitalized cost'), ('usage', 'Usage reading'), ('maintenance', 'Maintenance'), ('estimate_change', 'Prospective estimate change'), ('impairment', 'Impairment'), ('transfer', 'Transfer / custodian change'), ('disposal', 'Disposal')], db_index=True, max_length=30)),
                ('event_date', models.DateField(db_index=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('details', models.JSONField(default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='finance.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_lifecycle_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date', '-pk'],
                'indexes': [models.Index(fields=['asset', 'event_type', 'event_date'], name='finance_ass_asset_i_1d6041_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryUnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_unit', models.CharField(max_length=40)),
                ('to_base_multiplier', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_conversions', to='finance.consumableitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'from_unit'), name='unique_inventory_item_unit')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('receipt', 'Supplier receipt'), ('issue', 'Issue'), ('return', 'Return'), ('transfer', 'Transfer'), ('waste', 'Waste'), ('expiry', 'Expiry'), ('adjustment', 'Adjustment')], db_index=True, max_length=20)),
                ('movement_date', models.DateField(db_index=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='poultry.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='finance.inventorylocation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.consumableitem')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.sharedconsumablelot')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='finance.inventorylocation')),
                ('usage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movement', to='finance.consumableusage')),
            ],
            options={
                'ordering': ['-movement_date', '-pk'],
                'indexes': [models.Index(fields=['item', 'movement_date'], name='finance_sto_item_id_d00615_idx'), models.Index(fields=['batch', 'movement_date'], name='finance_sto_batch_i_d706db_idx')],
            },
        ),
    ]
