# Generated by Django 6.0.6 on 2026-09-18 19:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_employeeprofile_first_name_employeeprofile_last_name'),
        ('poultry', '0032_sales_receivable_follow_up_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerReceiptDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('designation_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('reversed', 'Reversed')], db_index=True, default='posted', max_length=20)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-designation_date', '-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='fundingreceipt',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Client-generated key used to safely retry contribution receipts.', max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fundingreceipt',
            name='request_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='fundingallocation',
            name='classification',
            field=models.CharField(choices=[('reinvestment', 'Reinvestment in Operations'), ('working_capital', 'Working Capital'), ('cost_recovery', 'Cost Recovery'), ('owner_distribution', 'Owner Profit Distribution'), ('owner_capital_return', 'Return of Owner Capital'), ('owner_drawing', 'Owner Drawing'), ('owner_compensation', 'Owner Compensation'), ('debt_service', 'Debt Service'), ('other', 'Other')], default='reinvestment', max_length=30),
        ),
        migrations.CreateModel(
            name='FinanceActionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('entity_type', models.CharField(db_index=True, max_length=80)),
                ('entity_id', models.CharField(blank=True, default='', max_length=120)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='OwnerContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_owner_contributors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Stable contributor identity for an OWNER_CAPITAL source.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funding_sources', to='finance.ownercontributor'),
        ),
        migrations.AddIndex(
            model_name='fundingsource',
            index=models.Index(fields=['source_type', 'owner'], name='finance_fun_source__ef9086_idx'),
        ),
        migrations.AddConstraint(
            model_name='fundingsource',
            constraint=models.CheckConstraint(condition=models.Q(('owner__isnull', True), ('source_type', 'owner_capital'), _connector='OR'), name='finance_funding_source_owner_only_for_capital'),
        ),
        migrations.AddField(
            model_name='ownerreceiptdesignation',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_capital_designations', to='poultry.batch'),
        ),
        migrations.AddField(
            model_name='ownerreceiptdesignation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_owner_designations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerreceiptdesignation',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_designations', to='finance.fundingreceipt'),
        ),
        migrations.AddField(
            model_name='ownerreceiptdesignation',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_owner_designations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='financeactionevent',
            index=models.Index(fields=['entity_type', 'entity_id'], name='finance_fin_entity__a6bd86_idx'),
        ),
        migrations.AddIndex(
            model_name='ownerreceiptdesignation',
            index=models.Index(fields=['receipt', 'status'], name='finance_own_receipt_75bb52_idx'),
        ),
        migrations.AddIndex(
            model_name='ownerreceiptdesignation',
            index=models.Index(fields=['batch', 'designation_date'], name='finance_own_batch_i_89e370_idx'),
        ),
        migrations.AddConstraint(
            model_name='ownerreceiptdesignation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'posted')), fields=('receipt', 'batch'), name='finance_one_posted_owner_designation_per_batch'),
        ),
    ]
