# Generated by Django 6.0.6 on 2026-09-24 12:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_ownerreceiptdesignation_and_more'),
        ('poultry', '0032_sales_receivable_follow_up_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(db_index=True, max_length=200)),
                ('customer_type', models.CharField(blank=True, default='', max_length=40)),
                ('contact_name', models.CharField(blank=True, default='', max_length=160)),
                ('phone', models.CharField(blank=True, default='', max_length=80)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('contribution_label', models.CharField(blank=True, choices=[('ideal', 'Ideal'), ('healthy', 'Healthy'), ('review', 'Review'), ('unprofitable', 'Unprofitable'), ('strategic_exception', 'Strategic Exception')], default='', max_length=30)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_customers', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_finance_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCostAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribution_date', models.DateField(db_index=True)),
                ('category', models.CharField(choices=[('direct_delivery', 'Direct Delivery Cost'), ('support', 'Support Cost'), ('rework', 'Rework Cost'), ('acquisition', 'Acquisition Cost')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('source_type', models.CharField(choices=[('expenditure', 'Expenditure'), ('payroll', 'Payroll Entry'), ('labour', 'Ad-hoc Labour'), ('cost_allocation', 'Batch Cost Allocation'), ('manual_estimate', 'Documented Estimate')], db_index=True, max_length=30)),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('economic_source_key', models.CharField(db_index=True, max_length=100)),
                ('source_label', models.CharField(max_length=255)),
                ('evidence_status', models.CharField(choices=[('actual', 'Actual / Source Linked'), ('estimated', 'Estimated')], db_index=True, default='actual', max_length=20)),
                ('attribution_basis', models.CharField(max_length=160)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('reversed', 'Reversed')], db_index=True, default='posted', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('request_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, default='')),
                ('accounting_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_cost_attributions', to='finance.accountingperiod')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_cost_attributions', to='poultry.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_cost_attributions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_attributions', to='finance.customer')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_customer_cost_attributions', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_cost_attributions', to='poultry.sales')),
            ],
            options={
                'ordering': ['-attribution_date', '-created_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active', 'display_name'], name='finance_cus_is_acti_c8ad27_idx'),
        ),
        migrations.AddIndex(
            model_name='customercostattribution',
            index=models.Index(fields=['customer', 'attribution_date'], name='finance_cus_custome_4c37cb_idx'),
        ),
        migrations.AddIndex(
            model_name='customercostattribution',
            index=models.Index(fields=['economic_source_key', 'status'], name='finance_cus_economi_c98f80_idx'),
        ),
        migrations.AddIndex(
            model_name='customercostattribution',
            index=models.Index(fields=['source_type', 'source_id'], name='finance_cus_source__b70500_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercostattribution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('evidence_status', 'estimated'), ('source_id__isnull', True), ('source_type', 'manual_estimate')), models.Q(('source_type', 'manual_estimate'), _negated=True), _connector='OR'), name='finance_manual_customer_cost_is_estimate'),
        ),
        migrations.AddConstraint(
            model_name='customercostattribution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_id__isnull', True), ('source_type', 'manual_estimate')), ('source_id__isnull', False), _connector='OR'), name='finance_customer_cost_source_identity'),
        ),
    ]
