# Generated by Django 6.0.6 on 2026-09-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_customer_customercostattribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollpayment',
            name='payment_kind',
            field=models.CharField(choices=[('advance', 'Salary advance'), ('salary', 'Salary payment')], db_index=True, default='salary', max_length=20),
        ),
    ]
