# Generated by Django 6.0.6 on 2026-07-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.CharField(choices=[('farm_manager', 'Farm Manager'), ('farm_supervisor', 'Farm Supervisor'), ('director', 'Director'), ('stake_holder', 'Stake Holder'), ('admin', 'Admin'), ('general_worker', 'General Worker')], max_length=64, unique=True),
        ),
    ]
